# See config-README.md for help on using this config file.
# To customize the settings, copy them to config-local.yaml. That file if present,
# will be used in place of this one

duration: 10

quadrants:
  top-left:
  - app:
    name: equalizer
    duration: 30
    scope: panel
    dispose-fn: equalizer_dispose
    persistent-draw: true
    args:
      external-filter: false
      side: left
      border: false  
  - app:
    name: time
    duration: 30
    scope: panel
    args:
      fmt_24_hour: false
      timezone:
  - app:
    name: cpu
    duration: 30
    animate: false
  - app:
    name: snap
    duration: 30
    animate: true
    scope: panel
    args:
      file: zigzag.json
      path: snapshot_files
      panel: left
  top-right:
  - app:
    name: equalizer
    duration: 30
    scope: panel
    dispose-fn: equalizer_dispose
    persistent-draw: true
    args:
      external-filter: false
      side: right
      border: false
  - app:
    name: weather
    duration: 30
    scope: panel
    args:
      units: imperial
      forecast: false
      forecast_day: 1
      forecast_hour: 12
      id_key_override: [forecast, weather_forecast, weather_current]
  - app:
    name: temp
    duration: 30
    animate: false
    scope: quadrant
  - app:
    name: snap
    animate: true
    duration: 30
    scope: panel
    args:
      file: every-third-row.json
      path: snapshot_files
      panel: right
  bottom-right:
  - app:
    name: noop1
    duration: 30
    display: false
  - app:
    name: noop2
    display: false
    duration: 30
  - app:
    name: fan
    duration: 30
    animate: false
  - app:
    name: noop3
    display: false
    duration: 30
  bottom-left:
  - app:
    name: noop1
    duration: 30
    display: false
  - app:
    name: noop2
    duration: 30
    display: false
  - app:
    name: mem-bat
    duration: 30
    animate: false
  - app:
    name: noop3
    duration: 30
    display: false
