[audio]
rate = 16000
fourier.downsample = 5
recorder = "cpal"
buffer = 16000
read_size = 256

# The following settings are curerntly ignored because not implemented in inputmodule-control
[fft]
length = 1024
window = "hann"

[equalizer]
columns = 9
rows = 34

# Logarithmic frequency band edges (Hz)
bands = [
  [30,   60],
  [60,   120],
  [120,  250],
  [250,  500],
  [500,  1000],
  [1000, 2000],
  [2000, 4000],
  [4000, 8000],
  [8000, 16000],
]

# Normalize energy per band
normalize = true

# Smooth vertical motion (important on tall matrices)
attack  = 0.6
decay   = 0.85

# Clamp noise floor
floor = 0.02
